name: check_run_example

on:
  push:
    branches:
      - main
      - dev
  check_run:
    types: [completed]
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.check_suite.head_branch == 'main'
    steps:
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.check_run.pull_requests[0].number
            })
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              body: "Making steady progress..."
            })
