name: discussion_comment_example

on:
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log discussion comment event
        run: |
          echo "A comment was made on a discussion!"
          echo """
          This workflow will run whenever a comment is made on a discussion in the repository.
          It simply logs a message to the console, but you can customize it to perform any actions you want based on the discussion_comment event.
          """
