name: gollum_example

on:
  gollum:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log gollum event
        run: |
          echo "Gollum event triggered!"
          echo """
          This workflow will run whenever a wiki page is created or edited in the repository.
          It simply logs a message to the console, but you can customize it to perform any actions you want based on the gollum event.
          """
