name: issue_comment_example

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log issue_comment event
        run: |
          echo "New issue comment added!"
          echo """
          This workflow will run whenever a new comment is added to an issue in the repository.
          It simply logs a message to the console, but you can customize it to perform any actions you want based on the issue_comment event.
          """
