name: push_example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log push event
        run: |
          echo "Push event triggered!"
          echo """
          This workflow will run whenever a push is made to the main branch of the repository.
          It simply logs a message to the console, but you can customize it to perform any actions you want based on the push event.
          """
