name: schedule

on:
  push:
    branches:
      - main
      - test-branch
  schedule:
    - cron: '*/3 * * * *'

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
    - name: Message action
      run: echo "You are great"