name: workflow_run_example

on:
  workflow_run:
    workflows: ["issues"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log workflow_run event
        run: |
          echo "A workflow run has completed!"
          echo """
          This workflow will run whenever a workflow run of the 'example-workflow' workflow completes.
          It simply logs a message to the console, but you can customize it to perform any actions you want based on the workflow_run event.
          """
